packages:
  - packages/*
  - apps/*

autoInstallPeers: false
engineStrict: true
strictPeerDependencies: true
sharedWorkspaceLockfile: true
preferFrozenLockfile: true
resolutionMode: highest

overrides:
  postcss: 8.5.26
  sharp: 0.35.3

onlyBuiltDependencies:
  - esbuild
